name: eval
description: A sample command-line application with basic argument parsing.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

resolution: workspace

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # cli

  # https://pub.dev/packages/args
  # args: ^2.7.0

  # https://pub.dev/packages/dart_eval
  dart_eval: ^0.8.2
  dp_basis:
    path: ../../dart_packages/dp_basis

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.2
